create schema cars;
select * from cars.car_dekho
use cars;
-- READDATA --
SELECT * FROM CAR_DEKHO;
-- TOTAL CARS TO GET COUNT OF TOTAL RECORDS --
SELECT COUNT(*) FROM CAR_DEKHO;
-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVAILABLE IN 2023--
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR=2023;
-- CARS AVAILABLE IN YEAR 2020,2021,2022--
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;
-- PRINT THE TOTAL OF ALL CARS BY YEAR DESCENDING ORDER--
SELECT YEAR,COUNT(*) AS 'SUM' FROM CAR_DEKHO GROUP BY YEAR ORDER BY SUM DESC;
-- HOW MANY DIESEL CARS IN YEAR 2020--
SELECT COUNT(*)  FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL="DIESEL"
-- HOW MANY PETROL CARS IN YEAR 2020--
SELECT COUNT(*)  FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL="PETROL";
-- PRINT ALL THE FUEL CARS (PETROL DIESEL AND CNG BY ALL YEAR --
SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "PETROL"  GROUP BY YEAR
SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "DIESEL"  GROUP BY YEAR
SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "CNG"  GROUP BY YEAR

-- WHICH YEAR HAD CARS MORE THAN 100 CARS--
SELECT YEAR, COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING COUNT(*)>100 ORDER BY COUNT(*) DESC

-- ALL CARS COUNT DETAILS BTWN 2015 AND 2023 --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023
